/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{vue,js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        ink: '#1d1d1f',
        graphite: '#707070',
        slate: '#474747',
        ash: '#333333',
        fog: '#f5f5f7',
        snow: '#ffffff',
        obsidian: '#000000',
        'silver-mist': '#e8e8ed',
        azure: '#0071e3',
        'cobalt-link': '#0066cc',
        'citrus-finish': '#dddc8c',
        'blush-finish': '#e8d0d0',
        'indigo-finish': '#596680',
        caution: '#b64400',
      },
      fontFamily: {
        display: ['Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        text: ['Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'caption': ['12px', '1.33'],
        'body-sm': ['14px', '1.43'],
        'body': ['17px', '1.47'],
        'subheading': ['20px', '1.4'],
        'heading-sm': ['24px', '1.29'],
        'heading': ['40px', '1.17'],
        'heading-lg': ['56px', '1.07'],
        'display': ['96px', '1.04'],
      },
      letterSpacing: {
        'caption': '-0.26px',
        'body-sm': '-0.04px',
        'body': '-0.1px',
        'subheading': '-0.2px',
        'heading-sm': '-0.36px',
        'heading': '-0.6px',
        'heading-lg': '-0.9px',
        'display': '-2.11px',
      },
      spacing: {
        '4': '4px',
        '8': '8px',
        '12': '12px',
        '16': '16px',
        '20': '20px',
        '24': '24px',
        '28': '28px',
        '32': '32px',
        '40': '40px',
        '44': '44px',
        '48': '48px',
        '52': '52px',
        '76': '76px',
        '80': '80px',
        '120': '120px',
        '144': '144px',
      },
      borderRadius: {
        'lg': '10px',
        '3xl': '28px',
        '3xl-2': '32px',
        '3xl-3': '36px',
        'full': '980px',
        'full-2': '999px',
        'cards': '28px',
        'buttons': '999px',
        'navitems': '980px',
        'pillbuttons': '999px',
        'featurelinks': '28px',
        'smallbuttons': '10px',
        'roundedbuttons': '36px',
      },
    },
  },
  plugins: [],
}
